# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLab4():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_lab4(self):
        self.driver.get("https://tutorialsninja.com/demo/")
        self.driver.find_element(By.LINK_TEXT, "Desktops").click()
        self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "input-sort").click()
        dropdown = self.driver.find_element(By.ID, "input-sort")
        dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".button-group > button:nth-child(1)").click()
        self.driver.find_element(By.NAME, "search").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) > .col-sm-4").click()
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "button-search").click()

