# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab5():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab5(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.set_window_size(1295, 687)
    self.driver.find_element(By.LINK_TEXT, "My Account").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-firstname").send_keys("Harika")
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.ID, "input-lastname").send_keys("Bollavaram")
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("testtilak28@gmail.com")
    self.driver.find_element(By.ID, "input-telephone").click()
    self.driver.find_element(By.ID, "input-telephone").send_keys("1234567890")
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("Harika@3703")
    self.driver.find_element(By.ID, "input-confirm").click()
    self.driver.find_element(By.ID, "input-confirm").send_keys("Harika@3703")
    self.driver.find_element(By.NAME, "newsletter").click()
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Address Book").click()
    self.driver.find_element(By.ID, "input-email").send_keys("testtilak28@gmail.com")
    self.driver.find_element(By.ID, "input-password").send_keys("Harika@3703")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "New Address").click()
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-firstname").send_keys("Harika")
    #self.driver.find_element(By.CSS_SELECTOR, "fieldset").click()
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.ID, "input-lastname").send_keys("Bollavaram")
    self.driver.find_element(By.ID, "input-address-1").click()
    self.driver.find_element(By.ID, "input-address-1").send_keys("11-10,Kurnool,Andhra Pradesh")
    self.driver.find_element(By.ID, "input-city").click()
    self.driver.find_element(By.ID, "input-city").send_keys("Kurnool")
    self.driver.find_element(By.ID, "input-postcode").click()
    self.driver.find_element(By.ID, "input-postcode").send_keys("123456")
    dropdown = self.driver.find_element(By.ID, "input-country")
    dropdown.find_element(By.XPATH, "//option[. = 'India']").click()
    element = self.driver.find_element(By.ID, "input-zone")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "input-zone")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "input-zone")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "input-zone").click()
    dropdown = self.driver.find_element(By.ID, "input-zone")
    dropdown.find_element(By.XPATH, "//option[. = 'Andhra Pradesh']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#input-zone > option:nth-child(3)").click()
    self.driver.find_element(By.NAME, "default").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Order History").click()
    self.driver.find_element(By.LINK_TEXT, "Continue").click()
    self.driver.find_element(By.LINK_TEXT, "View your order history").click()
  
